### ISSUE TITLE
Special character in mehtod toXMLString not getting escaped.

### ISSUE THREAD

**Issue by rest17** [tail-f-systems/JNC#90] opened 2020-05-11 22:22 UTC
String xml =                "<rpc xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\"\n"
                + "     message-id=\"3\">\n"
                + "  <edit-config xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n"
                + "    <config>\n"
                + "      <native>\n"
                + "        <ipv6>\n"
                + "          <dhcp>\n"
                + "            <pool>\n"
                + "              <name>QAZxswedcvgfyjuegrthnyjmkergthyjuerghtyjuerghtyc@#$%^&amp;*()(*&amp;^%$#@~QWERTYUIOPLKJHGFDSAZXCVBNM&lt;></name>\n"
                + "              <domain-names>example.com</domain-names>\n"
                + "              <dns-server>2001:db8:3000:3000::42</dns-server>\n"
                + "              <sntp>\n"
                + "                <address>2001:db8:2000:2000::33</address>\n"
                + "              </sntp>\n"
                + "            </pool>\n"
                + "          </dhcp>\n"
                + "        </ipv6>\n"
                + "      </native>\n"
                + "    </config>\n"
                + "  </edit-config>\n"
                + "</rpc>";
XMLParser parser=new XMLParser();
com.tailf.jnc.Element parse2=parser.parse( String xml);
com.tailf.jnc.Element config=parse2.getChild("<element tage name>?").getChild("<element tag name>");
System.out.println("Children Parser  "+ config.getChildren().toXMLString());

parse2.parse("<data>"+config.getChildren().toXMLString()+ "</data>") // this will fail since after parsing the xml once and then using toXMlString() to create the DOM object again with unescape character is causing it to fail.

**Comment by martin-volf** [comment] 2023-01-04 14:58
Duplicate of #76

**Closed** 2023-01-04 14:58 UTC
